# 1. Set up and module installation

In [80]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import os
import seaborn as sns
import statsmodels.api as sm
import numpy as np

In [81]:
#load our cleaned data in

In [82]:
data_path = "02_cleaned_data.csv"

In [83]:
data = pd.read_csv(data_path)

In [84]:
data.head()

Unnamed: 0  femaleh  hhsize  f0t6  m0t6     f7t12     m7t12    f13t15  \
0           0        0      10   0.0   0.0  0.000000  0.000000  0.100000   
1           1        0       7   0.0   0.0  0.142857  0.000000  0.000000   
2           2        0       6   0.0   0.0  0.000000  0.333333  0.166667   
3           3        0       5   0.0   0.0  0.000000  0.000000  0.000000   
4           4        0       3   0.0   0.0  0.000000  0.000000  0.000000   

     f16t18    f19t60  ...  m61  rural  Low_education  Low_income  Sumatra  \
0  0.100000  0.500000  ...  0.0      1            1.0         1.0        1   
1  0.142857  0.571429  ...  0.0      1            1.0         1.0        1   
2  0.166667  0.166667  ...  0.0      1            1.0         1.0        1   
3  0.200000  0.200000  ...  0.0      0            1.0         0.0        1   
4  0.000000  0.333333  ...  0.0      0            1.0         0.0        1   

   Java and Bali  Kalimantan  Sulawesi  Childlabour_05  Childlabour_06  
0              0           0         0               0               0  
1              0           0         0               0               1  
2              0           0         0               1               0  
3              0           0         0               1               1  
4              0           0         0               0               0  

[5 rows x 24 columns]

In [85]:
data=data.drop(["Unnamed: 0"], axis=1)

In [86]:
data.head()

femaleh  hhsize  f0t6  m0t6     f7t12     m7t12    f13t15    f16t18  \
0        0      10   0.0   0.0  0.000000  0.000000  0.100000  0.100000   
1        0       7   0.0   0.0  0.142857  0.000000  0.000000  0.142857   
2        0       6   0.0   0.0  0.000000  0.333333  0.166667  0.166667   
3        0       5   0.0   0.0  0.000000  0.000000  0.000000  0.200000   
4        0       3   0.0   0.0  0.000000  0.000000  0.000000  0.000000   

     f19t60  m13t15  ...  m61  rural  Low_education  Low_income  Sumatra  \
0  0.500000     0.0  ...  0.0      1            1.0         1.0        1   
1  0.571429     0.0  ...  0.0      1            1.0         1.0        1   
2  0.166667     0.0  ...  0.0      1            1.0         1.0        1   
3  0.200000     0.0  ...  0.0      0            1.0         0.0        1   
4  0.333333     0.0  ...  0.0      0            1.0         0.0        1   

   Java and Bali  Kalimantan  Sulawesi  Childlabour_05  Childlabour_06  
0              0           0         0               0               0  
1              0           0         0               0               1  
2              0           0         0               1               0  
3              0           0         0               1               1  
4              0           0         0               0               0  

[5 rows x 23 columns]

# 2. Get test and train splits, scale data

In [87]:
# Assign X (data) and y (target), reshape the y array
X = data.drop(["Childlabour_06"], axis=1)
y = data["Childlabour_06"]
print(X.shape, y.shape)

(4353, 22) (4353,)


In [88]:
#Split our data into training and testing

In [89]:
from sklearn.model_selection import train_test_split

In [90]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [91]:
type(X_test)

pandas.core.frame.DataFrame

In [92]:
X_test.shape

(1089, 22)

In [93]:
X_train.shape

(3264, 22)

In [94]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter = 10000)
classifier

LogisticRegression(max_iter=10000)

In [95]:
#Fit (train) or model using the training data

In [96]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

# 3. Check model fit

In [97]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.9399509803921569
Testing Data Score: 0.9393939393939394


In [98]:
predictions = classifier.predict(X_test)
print(f"First 10 Predictions:   {predictions[:10]}")
print(f"First 10 Actual labels: {y_test[:10].tolist()}")

First 10 Predictions:   [0 0 0 0 0 0 0 0 0 0]
First 10 Actual labels: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [99]:
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)

Prediction  Actual
0              0       0
1              0       0
2              0       0
3              0       0
4              0       0
...          ...     ...
1084           0       0
1085           0       1
1086           0       0
1087           0       0
1088           0       0

[1089 rows x 2 columns]

# 4. Analysis of first model

In [101]:
#Let's get a statistical summary of our logistic model
import statsmodels.api as sm
logit_model=sm.Logit(y,X)
result=logit_model.fit()
print(result.summary2())

Optimization terminated successfully.
         Current function value: 0.174815
         Iterations 9
                         Results: Logit
Model:              Logit            Pseudo R-squared: 0.225     
Dependent Variable: Childlabour_06   AIC:              1565.9358 
Date:               2020-10-26 02:05 BIC:              1706.2654 
No. Observations:   4353             Log-Likelihood:   -760.97   
Df Model:           21               LL-Null:          -981.98   
Df Residuals:       4331             LLR p-value:      1.7849e-80
Converged:          1.0000           Scale:            1.0000    
No. Iterations:     9.0000                                       
-----------------------------------------------------------------
                   Coef.  Std.Err.    z    P>|z|   [0.025  0.975]
-----------------------------------------------------------------
femaleh            0.4505   0.2948  1.5282 0.1265 -0.1273  1.0283
hhsize             0.1276   0.0464  2.7499 0.0060  0.0367  0.2186


In [102]:
#Hmmmmm... Low r-squared score. Damn
#Consider scaling household size?

In [103]:
#confusion matrix

In [104]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, predictions)
print(confusion_matrix)

[[1016   11]
 [  55    7]]


In [105]:
# Referring to documentation www.scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html
#the confusion matrix returns an output array as below for a binary target variable:
#  [(tn, fp, 
 #   fn, tp)]
    

In [106]:
#So the confusion matrix tells us of 1089 predictions in the X_test and y_test data set, there were 1014 True Negative results, 
#and 7 True Positives for a total of 1021 correct predictions


In [107]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.95      0.99      0.97      1027
           1       0.39      0.11      0.18        62

    accuracy                           0.94      1089
   macro avg       0.67      0.55      0.57      1089
weighted avg       0.92      0.94      0.92      1089



In [108]:
#So overall our initial model doesn't seem that great.
#We can implement some changes to make it work better

# 5. Implementing k-folds cross validation

In [109]:
# 
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
from numpy import mean
from numpy import std

In [110]:
# 
# prepare the cross-validation procedure
cv = KFold(n_splits=10, random_state=1, shuffle=True)
# evaluate model
scores_kfold = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores_kfold), std(scores_kfold)))


Accuracy: 0.938 (0.008)


In [111]:
# 
y_pred = cross_val_predict(classifier, X, y, cv=cv, n_jobs=-1)
conf_mat_kfold = confusion_matrix(y, y_pred)
conf_mat_kfold

array([[4062,   32],
       [ 237,   22]], dtype=int64)

In [112]:
# 
classification_report_kfold=classification_report(y, y_pred)
print(classification_report_kfold)

              precision    recall  f1-score   support

           0       0.94      0.99      0.97      4094
           1       0.41      0.08      0.14       259

    accuracy                           0.94      4353
   macro avg       0.68      0.54      0.55      4353
weighted avg       0.91      0.94      0.92      4353



In [113]:
# 
#Hmmm, interesting. So it seems recall has actually fallen slightly, whilst precision has increased. 
#Overall F1 and accuracy seems unchanged.
#This is likely because of the highly imbalanced nature of the data set- kfolds cross validation fails on highly imbalanced datasets
#To retify this we will create stratified k-fold cross-validation

# 6. Stratified k-fold cross validation

In [114]:
from sklearn.model_selection import StratifiedKFold

In [115]:
kstrat = StratifiedKFold(n_splits=5, shuffle=True, random_state=1)

In [116]:
# evaluate model
scores_kstrat = cross_val_score(classifier, X, y, scoring='accuracy', cv=kstrat, n_jobs=-1)
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores_kstrat), std(scores_kstrat)))


Accuracy: 0.938 (0.002)


In [117]:
y_pred = cross_val_predict(classifier, X, y, cv=kstrat, n_jobs=-1)
conf_mat_kstrat = confusion_matrix(y, y_pred)
conf_mat_kstrat

array([[4065,   29],
       [ 240,   19]], dtype=int64)

In [118]:
classification_report_kstrat=classification_report(y, y_pred)
print(classification_report_kstrat)

              precision    recall  f1-score   support

           0       0.94      0.99      0.97      4094
           1       0.40      0.07      0.12       259

    accuracy                           0.94      4353
   macro avg       0.67      0.53      0.55      4353
weighted avg       0.91      0.94      0.92      4353



In [119]:
#So k-stratification didn't seem to help that much.
#Whilst we have ensured that there are an equal amount of y=1 observations in all our splits, still high imbalanced data set.
#So, we have tried to deal with imbalanced data by stratified sampling, but our data just seems too imbalanced to really fix this.
#So in our next step, we will attempt to train the model with more observation where y=1

# 7. Second model, using SMOTE

In [120]:
#Our quite bad at actually correctly identifying/predicting households where children go on to enter the labour market.
#This is likely due to the highly imblanced dataset we are using. We have tried k-folds cross validation, but this does not seem to have helped much
#Recalling our Exploratory Data Analysis only 5% of households actually have household labour- according to our survey earlier

In [121]:
from imblearn.over_sampling import SMOTE

In [122]:
os = SMOTE(random_state=0)


In [123]:
y_train.value_counts()

0    3067
1     197
Name: Childlabour_06, dtype: int64

In [124]:
smt = SMOTE()
X_train_os, y_train_os = smt.fit_sample(X_train, y_train)

In [125]:
np.bincount(y_train_os)

array([3067, 3067], dtype=int64)

In [126]:
#We now have perfectly balanced sample sizes in our training data set

In [127]:
classifier.fit(X_train_os, y_train_os)

LogisticRegression(max_iter=10000)

In [128]:
print(f"Training Data Score: {classifier.score(X_train_os, y_train_os)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.7738832735572221
Testing Data Score: 0.7640036730945822


In [129]:
predictions = classifier.predict(X_test)

In [130]:
type(predictions)

numpy.ndarray

In [131]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.98      0.77      0.86      1027
           1       0.15      0.68      0.25        62

    accuracy                           0.76      1089
   macro avg       0.56      0.72      0.55      1089
weighted avg       0.93      0.76      0.83      1089



In [132]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, predictions)
print(confusion_matrix)

[[790 237]
 [ 20  42]]


In [133]:
#Hmmm, so our accuracy and our precision have decreased somewhat, 
#However, we are picking up more true positives and our recall has improved after using SMOTE, without too much decrease in F1 score

In [134]:
#Let's get a statistical summary of our logistic model
import statsmodels.api as sm
logit_model2=sm.Logit(y_train_os, X_train_os)
result2=logit_model2.fit()
print(result2.summary2())

Optimization terminated successfully.
         Current function value: 0.479343
         Iterations 7
                         Results: Logit
Model:              Logit            Pseudo R-squared: 0.308    
Dependent Variable: Childlabour_06   AIC:              5924.5776
Date:               2020-10-26 02:06 BIC:              6072.4529
No. Observations:   6134             Log-Likelihood:   -2940.3  
Df Model:           21               LL-Null:          -4251.8  
Df Residuals:       6112             LLR p-value:      0.0000   
Converged:          1.0000           Scale:            1.0000   
No. Iterations:     7.0000                                      
----------------------------------------------------------------
                 Coef.  Std.Err.    z     P>|z|   [0.025  0.975]
----------------------------------------------------------------
femaleh         -0.6017   0.1706  -3.5275 0.0004 -0.9360 -0.2674
hhsize           0.1131   0.0239   4.7231 0.0000  0.0662  0.1600
f0t6         

# 8. Combining SMOTE and repeated K-folds validation

In [135]:
#So our minority over-sampling approach using SMOTE seemed to work well.
#Now that we have balanced data, we can also be a bit more confident that any cross-validation will also likely work better
#Let's see if we can't combine repeated kfolds validation and SMOTE to get a better model fitting process.

In [136]:
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import cross_val_score

In [137]:
#We could simply load in our oversampled dataset created in Section 7 and then apply kfolds.
#However, to avoid overfitting we want to split into training and testing folds. 
#and then on each fold we want to oversample, train classifier and then validate
#Happily, we can actually create code that runs this all for us, using pipeline

In [138]:
cv_os = KFold(n_splits=10, random_state=1, shuffle=True)

In [139]:
from imblearn.pipeline import Pipeline, make_pipeline

In [140]:
imb_pipeline = make_pipeline(SMOTE(random_state=42), 
                              LogisticRegression(max_iter = 1000))
cross_val_score(imb_pipeline, X_train, y_train, scoring='recall', cv=cv_os)

array([0.55555556, 0.80952381, 0.57142857, 0.77777778, 0.82608696,
       0.53846154, 0.71428571, 0.78947368, 0.63157895, 0.47058824])

In [141]:
result3=imb_pipeline.fit( X_train, y_train)

In [142]:
y_test_os_predict=imb_pipeline.predict(X_test)


In [143]:
y_os_kf_pred=pd.Series(y_test_os_predict)

In [144]:
print(classification_report(y_test, y_os_kf_pred))

              precision    recall  f1-score   support

           0       0.98      0.78      0.87      1027
           1       0.16      0.68      0.25        62

    accuracy                           0.77      1089
   macro avg       0.57      0.73      0.56      1089
weighted avg       0.93      0.77      0.83      1089



In [145]:
from sklearn.metrics import confusion_matrix
confusion_matrix_hat = confusion_matrix(y_test, y_os_kf_pred)
print(confusion_matrix_hat)

[[801 226]
 [ 20  42]]


In [146]:
print(result3.summary())

AttributeError: 'Pipeline' object has no attribute 'summary'

In [147]:
#-------------------------------------------------------------------------------------------------------
#What happens if we just use cross-validation on previously created over-sampled datset?

In [148]:
# prepare the cross-validation procedure
hat2 = KFold(n_splits=10, random_state=1, shuffle=True)
# evaluate model
logreg=LogisticRegression(max_iter = 1000)
scores_kfold = cross_val_score(logreg, X_train_os, y_train_os, scoring='accuracy', cv=hat2, n_jobs=-1)
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores_kfold), std(scores_kfold)))

Accuracy: 0.772 (0.014)


In [149]:
# 
y_pred_os = cross_val_predict(logreg, X_test, y_test, cv=cv, n_jobs=-1)
conf_mat_hat2 = confusion_matrix(y_test, y_pred_os)
conf_mat_hat2

array([[1022,    5],
       [  59,    3]], dtype=int64)

In [150]:
# 
classification_report_hat2=classification_report(y_test, y_pred_os)
print(classification_report_hat2)

              precision    recall  f1-score   support

           0       0.95      1.00      0.97      1027
           1       0.38      0.05      0.09        62

    accuracy                           0.94      1089
   macro avg       0.66      0.52      0.53      1089
weighted avg       0.91      0.94      0.92      1089



# 9. Feature Selection using Recursive Feature Elimination

In [151]:
from sklearn.feature_selection import RFE
from sklearn.feature_selection import RFECV

In [152]:
logreg_rfe = LogisticRegression(max_iter = 1000)

In [153]:
rfe = RFE(logreg_rfe, n_features_to_select=10)

In [154]:
rfe = rfe.fit(X_train, y_train.values.ravel())
print(rfe.support_)
print(rfe.ranking_)

[False False  True  True  True False  True False  True  True  True  True
  True False False False False False False False False  True]
[ 8 10  1  1  1  9  1  5  1  1  1  1  1  2  4  3 12  6  7 11 13  1]


In [155]:
# summarize all features
for i in range(X_train_os.shape[1]):
    print('Column: %d, Selected %s, Rank: %.3f' % (i, rfe.support_[i], rfe.ranking_[i]))

Column: 0, Selected False, Rank: 8.000
Column: 1, Selected False, Rank: 10.000
Column: 2, Selected True, Rank: 1.000
Column: 3, Selected True, Rank: 1.000
Column: 4, Selected True, Rank: 1.000
Column: 5, Selected False, Rank: 9.000
Column: 6, Selected True, Rank: 1.000
Column: 7, Selected False, Rank: 5.000
Column: 8, Selected True, Rank: 1.000
Column: 9, Selected True, Rank: 1.000
Column: 10, Selected True, Rank: 1.000
Column: 11, Selected True, Rank: 1.000
Column: 12, Selected True, Rank: 1.000
Column: 13, Selected False, Rank: 2.000
Column: 14, Selected False, Rank: 4.000
Column: 15, Selected False, Rank: 3.000
Column: 16, Selected False, Rank: 12.000
Column: 17, Selected False, Rank: 6.000
Column: 18, Selected False, Rank: 7.000
Column: 19, Selected False, Rank: 11.000
Column: 20, Selected False, Rank: 13.000
Column: 21, Selected True, Rank: 1.000


In [156]:
type(X_train_os)

pandas.core.frame.DataFrame

In [157]:
X_train_os.iloc[:, [2,3,4,6,8,9,10,11,12,21]].head()

f0t6  m0t6  f7t12  f13t15    f19t60  m13t15  m16t18    m19t60  f61  \
0  0.000000   0.0    0.0     0.0  0.250000     0.0     0.0  0.250000  0.0   
1  0.000000   0.0    0.0     0.0  0.500000     0.0     0.0  0.500000  0.0   
2  0.285714   0.0    0.0     0.0  0.285714     0.0     0.0  0.428571  0.0   
3  0.000000   0.0    0.2     0.0  0.200000     0.0     0.2  0.200000  0.0   
4  0.000000   0.0    0.0     0.2  0.200000     0.0     0.0  0.200000  0.0   

   Childlabour_05  
0               0  
1               0  
2               0  
3               1  
4               0