# Set up and module installation

In [46]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import os
import seaborn as sns
import statsmodels.api as sm
import numpy as np

In [47]:
#load our cleaned data in

In [48]:
data_path = "cleaned_data.csv"

In [49]:
data = pd.read_csv(data_path)

In [50]:
data.head()

Unnamed: 0  femaleh  hhsize  f0t6  m0t6     f7t12     m7t12    f13t15  \
0           0        0      10   0.0   0.0  0.000000  0.000000  0.100000   
1           1        0       7   0.0   0.0  0.142857  0.000000  0.000000   
2           2        0       6   0.0   0.0  0.000000  0.333333  0.166667   
3           3        0       5   0.0   0.0  0.000000  0.000000  0.000000   
4           4        0       3   0.0   0.0  0.000000  0.000000  0.000000   

     f16t18    f19t60  ...  Quintile 1  Quintile 2  Quintile 3  Quintile 4  \
0  0.100000  0.500000  ...           1           0           0           0   
1  0.142857  0.571429  ...           1           0           0           0   
2  0.166667  0.166667  ...           1           0           0           0   
3  0.200000  0.200000  ...           0           1           0           0   
4  0.000000  0.333333  ...           0           0           0           0   

   Sumatra  Java and Bali  Kalimantan  Sulawesi  Childlabour_05  \
0        1              0           0         0               0   
1        1              0           0         0               0   
2        1              0           0         0               1   
3        1              0           0         0               1   
4        1              0           0         0               0   

   Childlabour_06  
0               0  
1               1  
2               0  
3               1  
4               0  

[5 rows x 30 columns]

In [51]:
data=data.drop(["Unnamed: 0"], axis=1)

In [52]:
data.head()

femaleh  hhsize  f0t6  m0t6     f7t12     m7t12    f13t15    f16t18  \
0        0      10   0.0   0.0  0.000000  0.000000  0.100000  0.100000   
1        0       7   0.0   0.0  0.142857  0.000000  0.000000  0.142857   
2        0       6   0.0   0.0  0.000000  0.333333  0.166667  0.166667   
3        0       5   0.0   0.0  0.000000  0.000000  0.000000  0.200000   
4        0       3   0.0   0.0  0.000000  0.000000  0.000000  0.000000   

     f19t60  m13t15  ...  Quintile 1  Quintile 2  Quintile 3  Quintile 4  \
0  0.500000     0.0  ...           1           0           0           0   
1  0.571429     0.0  ...           1           0           0           0   
2  0.166667     0.0  ...           1           0           0           0   
3  0.200000     0.0  ...           0           1           0           0   
4  0.333333     0.0  ...           0           0           0           0   

   Sumatra  Java and Bali  Kalimantan  Sulawesi  Childlabour_05  \
0        1              0           0         0               0   
1        1              0           0         0               0   
2        1              0           0         0               1   
3        1              0           0         0               1   
4        1              0           0         0               0   

   Childlabour_06  
0               0  
1               1  
2               0  
3               1  
4               0  

[5 rows x 29 columns]

# Get test and train splits, scale data

In [53]:
# Assign X (data) and y (target), reshape the y array
X = data.drop(["Childlabour_06"], axis=1)
y = data["Childlabour_06"]
print(X.shape, y.shape)

(4353, 28) (4353,)


In [54]:
#Split our data into training and testing

In [55]:
from sklearn.model_selection import train_test_split

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [57]:
type(X_test)

pandas.core.frame.DataFrame

In [58]:
X_test.shape

(1089, 28)

In [59]:
X_train.shape

(3264, 28)

In [60]:
#Scale our data

In [61]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter = 10000)
classifier

LogisticRegression(max_iter=10000)

In [62]:
#Fit (train) or model using the training data

In [63]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

# Check model fit

In [64]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.9402573529411765
Testing Data Score: 0.9375573921028466


In [65]:
predictions = classifier.predict(X_test)
print(f"First 10 Predictions:   {predictions[:10]}")
print(f"First 10 Actual labels: {y_test[:10].tolist()}")

First 10 Predictions:   [0 0 0 0 0 0 0 0 0 0]
First 10 Actual labels: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [66]:
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)

Prediction  Actual
0              0       0
1              0       0
2              0       0
3              0       0
4              0       0
...          ...     ...
1084           0       0
1085           0       1
1086           0       0
1087           0       0
1088           0       0

[1089 rows x 2 columns]

In [67]:
#Let's get a statistical summary of our logistic model
import statsmodels.api as sm
logit_model=sm.Logit(y,X)
result=logit_model.fit()
print(result.summary2())

Optimization terminated successfully.
         Current function value: 0.173464
         Iterations 9
                            Results: Logit
Model:                 Logit             Pseudo R-squared:  0.231     
Dependent Variable:    Childlabour_06    AIC:               1566.1812 
Date:                  2020-10-24 03:43  BIC:               1744.7826 
No. Observations:      4353              Log-Likelihood:    -755.09   
Df Model:              27                LL-Null:           -981.98   
Df Residuals:          4325              LLR p-value:       5.0302e-79
Converged:             1.0000            Scale:             1.0000    
No. Iterations:        9.0000                                         
----------------------------------------------------------------------
                        Coef.  Std.Err.    z    P>|z|   [0.025  0.975]
----------------------------------------------------------------------
femaleh                 0.4588   0.2975  1.5422 0.1230 -0.1243  1.0418
hhs

In [54]:
#Hmmmmm this doesn't look quite right to be honest- no education or income quintiles are showing as statistically significant
#Low r-squared score. Damn
#May need to add in the last of each dummy variables. 
#Consider scaling household size?

# Analysis of initial model performance

In [55]:
#confusion matrix

In [56]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, predictions)
print(confusion_matrix)

[[1016   11]
 [  55    7]]


In [57]:
# Referring to documentation www.scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html
#the confusion matrix returns an output array as below for a binary target variable:
#  [(tn, fp, 
 #   fn, tp)]
    

In [58]:
#So the confusion matrix tells us of 1089 predictions in the X_test and y_test data set, there were 1016 True Negative results, 
#and 7 True Positives for a total of 1025 correct predictions


In [79]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.95      0.99      0.97      1027
           1       0.35      0.11      0.17        62

    accuracy                           0.94      1089
   macro avg       0.65      0.55      0.57      1089
weighted avg       0.91      0.94      0.92      1089



In [60]:
#So overall our model doesn't seem that great.
#It seems quite bad at actually correctly identifying/predicting households where children go on to enter the labour market.
#This may be due to the highly imblanced dataset we are using, 
#Recalling our Exploratory Data Analysis only 5% of households actually have household labour- according to our survey earlier

# Second model, using SMOTE

In [61]:
from imblearn.over_sampling import SMOTE

In [62]:
os = SMOTE(random_state=0)


In [63]:
y_train.value_counts()

0    3067
1     197
Name: Childlabour_06, dtype: int64

In [64]:
smt = SMOTE()
X_train, y_train = smt.fit_sample(X_train, y_train)

In [65]:
np.bincount(y_train)

array([3067, 3067], dtype=int64)

In [66]:
#We now have perfectly balanced sample sizes in our training data set

In [67]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [68]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.8945223345288555
Testing Data Score: 0.9081726354453628


In [69]:
predictions = classifier.predict(X_test)

In [70]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.96      0.94      0.95      1027
           1       0.29      0.44      0.35        62

    accuracy                           0.91      1089
   macro avg       0.63      0.69      0.65      1089
weighted avg       0.93      0.91      0.92      1089



In [71]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, predictions)
print(confusion_matrix)

[[962  65]
 [ 35  27]]


In [ ]:
#Hmmm, so our accuracy has precision somewhat, 
#However, we are picking up more true positives and our recall has improved after using SMOTE, without too much decrease in F1 score

# Implementing k-folds cross validation

In [74]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
from numpy import mean
from numpy import std

In [75]:
# prepare the cross-validation procedure
cv = KFold(n_splits=10, random_state=1, shuffle=True)
# evaluate model
scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))


Accuracy: 0.937 (0.006)


In [77]:
y_pred = cross_val_predict(classifier, X, y, cv=cv, n_jobs=-1)
conf_mat = confusion_matrix(y, y_pred)
conf_mat

array([[4059,   35],
       [ 238,   21]], dtype=int64)

In [80]:
print(classification_report(y, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.99      0.97      4094
           1       0.38      0.08      0.13       259

    accuracy                           0.94      4353
   macro avg       0.66      0.54      0.55      4353
weighted avg       0.91      0.94      0.92      4353



In [ ]:
#hmmm, not so good it seems