# Set up and module installation

In [122]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import os
import seaborn as sns
import statsmodels.api as sm
import numpy as np

In [87]:
#load our cleaned data in

In [88]:
data_path = "cleaned_data.csv"

In [89]:
data = pd.read_csv(data_path)

In [90]:
data.head()

Unnamed: 0  femaleh  hhsize  f0t6  m0t6     f7t12     m7t12    f13t15  \
0           0        0      10   0.0   0.0  0.000000  0.000000  0.100000   
1           1        0       7   0.0   0.0  0.142857  0.000000  0.000000   
2           2        0       6   0.0   0.0  0.000000  0.333333  0.166667   
3           3        0       5   0.0   0.0  0.000000  0.000000  0.000000   
4           4        0       3   0.0   0.0  0.000000  0.000000  0.000000   

     f16t18    f19t60  ...  Sumatra  Java and Bali  Kalimantan  Sulawesi  \
0  0.100000  0.500000  ...        1              0           0         0   
1  0.142857  0.571429  ...        1              0           0         0   
2  0.166667  0.166667  ...        1              0           0         0   
3  0.200000  0.200000  ...        1              0           0         0   
4  0.000000  0.333333  ...        1              0           0         0   

   %work10t12  %work13t15  %work16t18  %work10t18  Childlabour_05  \
0         0.0         0.0    0.000000    0.000000               0   
1         0.0         0.0    0.000000    0.000000               0   
2         0.0         0.0    0.166667    0.166667               1   
3         0.0         0.0    0.200000    0.200000               1   
4         0.0         0.0    0.000000    0.000000               0   

   Childlabour_06  
0               0  
1               1  
2               0  
3               1  
4               0  

[5 rows x 37 columns]

In [91]:
data=data.drop(["Unnamed: 0"], axis=1)

In [92]:
data.head()

femaleh  hhsize  f0t6  m0t6     f7t12     m7t12    f13t15    f16t18  \
0        0      10   0.0   0.0  0.000000  0.000000  0.100000  0.100000   
1        0       7   0.0   0.0  0.142857  0.000000  0.000000  0.142857   
2        0       6   0.0   0.0  0.000000  0.333333  0.166667  0.166667   
3        0       5   0.0   0.0  0.000000  0.000000  0.000000  0.200000   
4        0       3   0.0   0.0  0.000000  0.000000  0.000000  0.000000   

     f19t60  m13t15  ...  Sumatra  Java and Bali  Kalimantan  Sulawesi  \
0  0.500000     0.0  ...        1              0           0         0   
1  0.571429     0.0  ...        1              0           0         0   
2  0.166667     0.0  ...        1              0           0         0   
3  0.200000     0.0  ...        1              0           0         0   
4  0.333333     0.0  ...        1              0           0         0   

   %work10t12  %work13t15  %work16t18  %work10t18  Childlabour_05  \
0         0.0         0.0    0.000000    0.000000               0   
1         0.0         0.0    0.000000    0.000000               0   
2         0.0         0.0    0.166667    0.166667               1   
3         0.0         0.0    0.200000    0.200000               1   
4         0.0         0.0    0.000000    0.000000               0   

   Childlabour_06  
0               0  
1               1  
2               0  
3               1  
4               0  

[5 rows x 36 columns]

# Get test and train splits, scale data

In [93]:
# Assign X (data) and y (target), reshape the y array
X = data.drop(["Childlabour_06"], axis=1)
y = data["Childlabour_06"]
print(X.shape, y.shape)

(4353, 35) (4353,)


In [94]:
#Split our data into training and testing

In [95]:
from sklearn.model_selection import train_test_split

In [96]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [97]:
type(X_test)

pandas.core.frame.DataFrame

In [98]:
X_test.shape

(1089, 35)

In [99]:
X_train.shape

(3264, 35)

In [50]:
#Scale our data

In [51]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)


In [52]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [100]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter = 10000)
classifier

LogisticRegression(max_iter=10000)

In [101]:
#Fit (train) or model using the training data

In [102]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

# Check model fit

In [103]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.9420955882352942
Testing Data Score: 0.9393939393939394


In [104]:
predictions = classifier.predict(X_test)
print(f"First 10 Predictions:   {predictions[:10]}")
print(f"First 10 Actual labels: {y_test[:10].tolist()}")

First 10 Predictions:   [0 0 0 0 0 0 0 0 0 0]
First 10 Actual labels: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [105]:
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)

Prediction  Actual
0              0       0
1              0       0
2              0       0
3              0       0
4              0       0
...          ...     ...
1084           0       0
1085           0       1
1086           0       0
1087           0       0
1088           0       0

[1089 rows x 2 columns]

In [106]:
#Let's get a statistical summary of our logistic model
import statsmodels.api as sm
logit_model=sm.Logit(y,X)
result=logit_model.fit()
print(result.summary2())

Optimization terminated successfully.
         Current function value: 0.170735
         Iterations 9
                                  Results: Logit
Model:                     Logit                 Pseudo R-squared:      0.243     
Dependent Variable:        Childlabour_06        AIC:                   1550.4229 
Date:                      2020-10-22 01:13      BIC:                   1754.5388 
No. Observations:          4353                  Log-Likelihood:        -743.21   
Df Model:                  31                    LL-Null:               -981.98   
Df Residuals:              4321                  LLR p-value:           1.9338e-81
Converged:                 1.0000                Scale:                 1.0000    
No. Iterations:            9.0000                                                 
----------------------------------------------------------------------------------
                  Coef.     Std.Err.      z    P>|z|      [0.025         0.975]   
-------------------

In [107]:
#Hmmmmm this doesn't look quite right to be honest- no education or income quintiles are showing as statistically significant
#Low r-squared score. Damn
#May need to add in the last of each dummy variables. 
#Consider scaling household size?

# Analysis of Model performance

In [108]:
#confusion matrix

In [109]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, predictions)
print(confusion_matrix)

[[1016   11]
 [  55    7]]


In [110]:
# Referring to documentation www.scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html
#the confusion matrix returns an output array as below for a binary target variable:
#  [(tn, fp, 
 #   fn, tp)]
    

In [111]:
#So the confusion matrix tells us of 1089 predictions in the X_test and y_test data set, there were 1016 True Negative results, 
#and 7 True Positives for a total of 1025 correct predictions


In [112]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.95      0.99      0.97      1027
           1       0.39      0.11      0.18        62

    accuracy                           0.94      1089
   macro avg       0.67      0.55      0.57      1089
weighted avg       0.92      0.94      0.92      1089



In [113]:
#So overall our model doesn't seem that great.
#It seems quite bad at actually correctly identifying/predicting households where children go on to enter the labour market.
#This may be due to the highly imblanced dataset we are using, 
#Recalling our Exploratory Data Analysis only 5% of households actually have household labour- according to our survey earlier

In [114]:
from imblearn.over_sampling import SMOTE

In [115]:
os = SMOTE(random_state=0)


In [119]:
y_train.value_counts()

0    2868
1     179
Name: Childlabour_06, dtype: int64

In [120]:
smt = SMOTE()
X_train, y_train = smt.fit_sample(X_train, y_train)

In [123]:
np.bincount(y_train)

array([2868, 2868], dtype=int64)

In [128]:
#We now have perfectly balanced sample sizes in our training data set

In [129]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [130]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.8952231520223152
Testing Data Score: 0.9081163859111792


In [127]:
predictions = classifier.predict(X_test)

In [131]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.96      0.94      0.95      1226
           1       0.32      0.45      0.38        80

    accuracy                           0.91      1306
   macro avg       0.64      0.69      0.66      1306
weighted avg       0.92      0.91      0.92      1306



In [133]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, predictions)
print(confusion_matrix)

[[1150   76]
 [  44   36]]


In [ ]:
#Hmmm, so our accuracy has decreased somewhat, 
#However, we are picking up more true positives and our recall has improved after using SMOTE